name: End-to-end tests
on: push
jobs:
    cypress-run:
        runs-on: ubuntu-22.04
        env:
            VITE_GEO_API_KEY: ${{ secrets.VITE_GEO_API_KEY}}
            VITE_WEATHER_API_KEY: ${{ secrets.VITE_WEATHER_API_KEY}}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            # Install npm dependencies, cache them correctly
            # and run all Cypress tests
            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                  start: npm run dev
